### ISSUE TITLE
client_credentials requires the client_secret block even if it's not used

### ISSUE THREAD

**Issue by rkl3ss** [iwarapter/terraform-provider-pingaccess#116]
On the _pingaccess_websession_ resource, the _client_credentials_ nested block makes Terraform crash if the _client_secret_ element is not included, even if in certain cases it's not needed (e.g. using _credentials_type = "PRIVATE_KEY_JWT"_).
The same happens within the _pingaccess_pingfederate_oauth_ resource, which basically contains the same nested block. In both cases, the _client_secret_ element is stated as optional in the documentation.

For instance, the following resource:

```
resource "pingaccess_websession" "my_web_session" {
  name = "my web session"
  audience = "my_audience"

  client_credentials {
    client_id = "my_client_id"
    credentials_type = "PRIVATE_KEY_JWT"
  }
}
```

Would cause an error like the following:

```
Stack trace from the terraform-provider-pingaccess_v0.8.0 plugin:

panic: interface conversion: interface {} is nil, not []map[string]interface {}

goroutine 270 [running]:
github.com/iwarapter/terraform-provider-pingaccess/internal/sdkv2provider.setClientCredentials(0xc000327180, 0xc00006f420, 0x1, 0xc00051af00)
        /home/runner/work/terraform-provider-pingaccess/terraform-provider-pingaccess/internal/sdkv2provider/structures.go:550 +0xa94
github.com/iwarapter/terraform-provider-pingaccess/internal/sdkv2provider.resourcePingAccessWebSessionReadResult(0xc000327180, 0xc000500d00, 0xece101, 0xc00000f6d8, 0xecb018, 0xc00000f6e0)
        /home/runner/work/terraform-provider-pingaccess/terraform-provider-pingaccess/internal/sdkv2provider/resource_pingaccess_websession.go:261 +0x64e
github.com/iwarapter/terraform-provider-pingaccess/internal/sdkv2provider.resourcePingAccessWebSessionCreate(0xec3008, 0xc000365680, 0xc000327180, 0xda75e0, 0xc00047b500, 0xc00016d540, 0xb419aa, 0xc000431020)
        /home/runner/work/terraform-provider-pingaccess/terraform-provider-pingaccess/internal/sdkv2provider/resource_pingaccess_websession.go:188 +0x385
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000240460, 0xec2f98, 0xc0004c0700, 0xc000327180, 0xda75e0, 0xc00047b500, 0x0, 0x0, 0x0)
        /home/runner/work/terraform-provider-pingaccess/terraform-provider-pingaccess/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:330 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000240460, 0xec2f98, 0xc0004c0700, 0xc0000aa930, 0xc000431020, 0xda75e0, 0xc00047b500, 0x0, 0x0, 0x0, ...)
        /home/runner/work/terraform-provider-pingaccess/terraform-provider-pingaccess/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000272468, 0xec2f98, 0xc0004c0700, 0xc0003efbd0, 0xc00038e2e8, 0x1, 0x30)
        /home/runner/work/terraform-provider-pingaccess/terraform-provider-pingaccess/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-mux.SchemaServer.ApplyResourceChange(0xc000292e40, 0xc000292e70, 0xc000339c20, 0x2, 0x2, 0xc0000daa00, 0x1, 0xec2f98, 0xc0004c0700, 0xc0003efbd0, ...)
        /home/runner/work/terraform-provider-pingaccess/terraform-provider-pingaccess/vendor/github.com/hashicorp/terraform-plugin-mux/schema_server.go:287 +0x98
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000339ca0, 0xec3040, 0xc0004c0700, 0xc0000aa7e0, 0xc000339ca0, 0xc000277dd0, 0xc0001a9ba0)
        /home/runner/work/terraform-provider-pingaccess/terraform-provider-pingaccess/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xd70240, 0xc000339ca0, 0xec3040, 0xc000277dd0, 0xc0003652c0, 0x0, 0xec3040, 0xc000277dd0, 0xc000013700, 0x523)
        /home/runner/work/terraform-provider-pingaccess/terraform-provider-pingaccess/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000180e00, 0xecb138, 0xc00039aa80, 0xc000374360, 0xc000292f00, 0x1336360, 0x0, 0x0, 0x0)
        /home/runner/work/terraform-provider-pingaccess/terraform-provider-pingaccess/vendor/google.golang.org/grpc/server.go:1297 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000180e00, 0xecb138, 0xc00039aa80, 0xc000374360, 0x0)
        /home/runner/work/terraform-provider-pingaccess/terraform-provider-pingaccess/vendor/google.golang.org/grpc/server.go:1626 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000294190, 0xc000180e00, 0xecb138, 0xc00039aa80, 0xc000374360)
        /home/runner/work/terraform-provider-pingaccess/terraform-provider-pingaccess/vendor/google.golang.org/grpc/server.go:941 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/work/terraform-provider-pingaccess/terraform-provider-pingaccess/vendor/google.golang.org/grpc/server.go:939 +0x1fd

Error: The terraform-provider-pingaccess_v0.8.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

A simple workaround is to add a dummy value for the secret, like in the following:

```
resource "pingaccess_websession" "my_web_session" {
  name = "my web session"
  audience = "my_audience"

  client_credentials {
    client_id = "my_client_id"
    credentials_type = "PRIVATE_KEY_JWT"
    client_secret {
      value = "dummy_unused_value"
    }
  }
}
```

This prevents Terraform from crashing, and you can have the configuration applied correctly.

I'm opening this issue mainly tho help other people that might face the same problem. The workaround is easy and I'd say a fix it's not urgent, it's barely a nice to have.
Another (temporary?) solution would be to add this information to the doc, reporting _client_secret_ as mandatory.

**Comment by iwarapter** [comment]
Which version of PingAccess does this run against?

**Comment by rkl3ss** [comment]
PingAccess 6.3.3.0
